export const COMMON_ITEMS = [
  'ID Card',
  'Institute ID Card',
  'Wallet',
  'Purse',
  'Cycle Keys',
  'Room Keys',
  'Hostel Keys',
  'Water Bottle',
  'Milton Bottle',
  'Cello Bottle',
  'Umbrella',
  'Raincoat',
  'Laptop',
  'Laptop Charger',
  'Mobile Phone',
  'Mobile Charger',
  'Earphones',
  'Headphones',
  'AirPods',
  'TWS Earbuds',
  'Scientific Calculator',
  'CASIO Calculator',
  'Calculator',
  'Lab Coat',
  'Engineering Drawing Kit',
  'Drafter',
  'T-Square',
  'File Folder',
  'Backpack',
  'Bag',
  'Gym Bag',
  'Spectacles',
  'Glasses',
  'Sunglasses',
  'Wrist Watch',
  'Smartwatch',
  'Pendrive',
  'USB Drive',
  'Hard Disk',
  'Power Bank',
  'Helmet',
  'Cycle',
  'Jacket',
  'Hoodie',
  'Sweater',
  'Shoes',
  'Sneakers',
  'Slippers',
  'Sandals',
  'Ring',
  'Necklace',
  'Bracelet',
  'Badminton Racket',
  'Table Tennis Bat',
  'Cricket Bat',
  'Football',
  'Basketball',
  'Computer Mouse',
  'Keyboard',
  'Tablet',
  'iPad',
  'Stylus',
  'Apple Pencil',
  'Kindle',
  'Library Book',
  'Course Book',
  'Notebook',
  'Rough Copy',
  'Pen',
  'Pencil Pouch',
  'Geometry Box',
  'Debit Card',
  'Credit Card',
  'Aadhar Card',
  'Driving License',
  'PAN Card',
  'Cash',
].sort();
